services:
  nginx:
    build:
      context: ./config
      dockerfile: nginx.dockerfile
    container_name: nginx
    privileged: true
    ports:
      - "3000:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./config
      dockerfile: php.dockerfile
    container_name: php
    privileged: true
    volumes:
      - ./www:/var/www/html
      - /usr/bin/gpioset:/usr/bin/gpioset
      - /dev:/dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
