version: '3.8'

services:
  nginx:
    image: nginx:1.26.2
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      php:
        condition: service_healthy
    restart: unless-stopped

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./www:/var/www/html
    devices:
      - "${GPIO_DEVICE}:/dev/gpiochip0"
    environment:
      GPIO_DEVICE: ${GPIO_DEVICE}
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
