services:
    php:
        build:
            context: .
            dockerfile: docker/php.Dockerfile
        container_name: php
        volumes:
            - ./www:/var/www/html
            - /proc/uptime:/host/proc/uptime:ro  # Mount host's /proc/uptime
        devices:
            - "${GPIO_DEVICE}:/dev/gpiochip0"
        environment:
            OS_VERSION: "${OS_VERSION:-}"
            DOCKER_VERSION: "${DOCKER_VERSION:-}"
            KERNEL_VERSION: "${KERNEL_VERSION:-}"
            DEVICE: "${DEVICE:-}"
            GPIO_DEVICE: ${GPIO_DEVICE:-}
            DOCKONTROL_URL: ${DOCKONTROL_URL}
            API_PUBLIC_KEY: ${API_PUBLIC_KEY}
            API_PRIVATE_KEY: ${API_PRIVATE_KEY}
            LEGACY_API_SECRET: ${LEGACY_API_SECRET:-}
            OPENWEBNET_IP: ${OPENWEBNET_IP:-}
            OPENWEBNET_PORT: ${OPENWEBNET_PORT:-}
            OPENWEBNET_PASSWORD: ${OPENWEBNET_PASSWORD:-}
            RELAY_BOARD_TYPE: ${RELAY_BOARD_TYPE:-}
            DOCKONTROL_NODE_VERSION: 2.0
        healthcheck:
            test: ["CMD-SHELL", "pgrep php-fpm"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: no
        networks:
            - app-network

    nginx:
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        container_name: nginx
        volumes:
            - ./www:/var/www/html
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./config/nginx/common.conf:/etc/nginx/conf.d/common.conf
        depends_on:
            php:
                condition: service_healthy
        ports:
            - "${NGINX_LISTEN_IP:-127.0.0.1}:80:80"
            - "${NGINX_LISTEN_IP:-127.0.0.1}:443:443"
        restart: no
        networks:
            - app-network

networks:
    app-network:
        driver: bridge