services:
    php:
        build:
            context: .
            dockerfile: docker/php.Dockerfile
        container_name: php
        volumes:
            - ./www:/var/www/html
        devices:
            - "${GPIO_DEVICE}:/dev/gpiochip0"
        environment:
            GPIO_DEVICE: ${GPIO_DEVICE}
            DOCKONTROL_URL: ${DOCKONTROL_URL}
            API_PUBLIC_KEY: ${API_PUBLIC_KEY}
            API_PRIVATE_KEY: ${API_PRIVATE_KEY}
        healthcheck:
            test: ["CMD-SHELL", "pgrep php-fpm"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        networks:
            - app-network

    nginx:
        image: nginx:1.26.2
        container_name: nginx
        volumes:
            - ./www:/var/www/html
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            php:
                condition: service_healthy
        ports:
            - "${WG0_IP}:80:80"
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge