services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: php
    volumes:
      - ./www:/var/www/html
      - sockets:/var/run/php
    devices:
      - "${GPIO_DEVICE}:/dev/gpiochip0"
    environment:
      GPIO_DEVICE: ${GPIO_DEVICE}
      DOCKONTROL_URL: ${DOCKONTROL_URL}
      API_PUBLIC_KEY: ${API_PUBLIC_KEY}
      API_PRIVATE_KEY: ${API_PRIVATE_KEY}
    cap_add:
      - NET_ADMIN
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm && [ -d /sys/class/net/wg0 ]"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: nginx
    volumes:
      - ./www:/var/www/html
      - sockets:/var/run/php
    depends_on:
      php:
        condition: service_healthy
    network_mode: host
    restart: unless-stopped

volumes:
  sockets:

